app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField, ValidationError, RadioField
from wtforms.validators import DataRequired, Email, EqualTo

from ..models import Tarefa

class FormularioTarefa(FlaskForm):
    """
    Formulario para usuario inserir uma nova tarefa
    """
    tarefa = StringField('Tarefa', validators=[DataRequired()])
    detalhe = StringField('Detalhe', validators=[DataRequired()])
    categoria = RadioField('Categoria', choices=[(1,'Azul'),(2,'Verde'),(3,'Agua'),(4,'Amarela'),(5,'Vermelha')])
    submit = SubmitField('Incluir')

    #def validate_tarefa(self, field):
    #    if field.tarefa.data is None:
    #        raise ValidationError('E necessario informar um nome para a tarefa.')

    #def validate_detalhe(self, field):
    #    if field.detalhe.data is None:
    #        raise ValidationError('E necessario informar um detalhamento para a tarefa.')

app/home/__init__.py
from flask import Blueprint


home = Blueprint('home', __name__)


from . import views

app/home/views.py
from flask import render_template, url_for
from flask_login import login_required
from werkzeug.utils import redirect

from app.home.forms import FormularioTarefa
from app.models import Tarefa
from . import home

@home.route('/')
def homepage():
    """
    Renderizando o template da pagina inicial no caminho /
    """
    return render_template('home/index.html', title="Seja Bem Vindo", title_painel="Organize o seu dia voce tambem")

@home.route('/dashboard', methods=['GET', 'POST'])
@login_required
def dashboard():
    """
    Inserindo tarefa pelo formulario
    """

    formulario = FormularioTarefa()
    if formulario.validate_on_submit():
        tarefa = Tarefa(tarefa=formulario.tarefa.data(),
                        detalhe=formulario.tarefa.data(),
                        categoria=formulario.tarefa.data())

        tarefa.persistir()

        # TODO: Recaregar aqui a listagem de tarefas utilizando ajax
        return redirect(url_for('home.dashboard'))

    # Renderizando o template da pagina inicial no caminho /dashboard
    return render_template('home/dashboard.html', title="Cadastro", form=formulario, title_painel="Cadastre sua tarefa")

app/templates/home/dashboard.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Cadastro{% endblock %}
{% block body %}
  <section name="formulario">

    <form class="form-horizontal" action="" method="post" role="form">
      {{ form.hidden_tag() }}
      {{ wtf.form_errors(form, hiddens="only") }}
      <br>
      <div class="form-group">
        <label for="tarefa" class="col-sm-2 control-label">Tarefa</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" id="tarefa" name="tarefa" required="" placeholder="Tarefa">
        </div>
      </div>

      <div class="form-group">
          <label for="detalhe" class="col-sm-2 control-label">Detalhe</label>
        <div class="col-sm-10">
          <textarea class="form-control" id="detalhe" name="detalhe" required="" placeholder="Detalhe" rows="3"></textarea>
        </div>
      </div>

      <div class="form-group">
            <label for="categoria" class="col-sm-2 control-label">Categoria</label>
        <div class="col-sm-10">
         <label class="radio-inline">
         <input type="radio" name="categoria" id="categoria-0" value="1"><span class="label label-primary"> Azul </span>
         </label>
         <label class="radio-inline">
         <input type="radio" name="categoria" id="categoria-1" value="2"><span class="label label-success"> Verde </span>
         </label>
         <label class="radio-inline">
         <input type="radio" name="categoria" id="categoria-2" value="3"><span class="label label-info"> Água </span>
         </label>
         <label class="radio-inline">
         <input type="radio" name="categoria" id="categoria-3" value="4"><span class="label label-warning"> Amarela </span>
         </label>
         <label class="radio-inline">
         <input type="radio" name="categoria" id="categoria-4" value="5"><span class="label label-danger"> Vermelha </span>
         </label>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-default">Incluir</button>
        </div>
      </div>
    </form>
  </section>
  
  <br>

  <ul class="list-group">
    <section class="todos">
		<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
		  <div class="panel panel-default">
		    <div class="panel-heading" role="tab" id="heading1">
		      <h4 class="panel-title">
		        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collaose1" aria-expanded="true" aria-controls="collaose1">
		            Tarefa 1
		        </a>
		      </h4>
		    </div>
		    <div id="collaose1" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading1">
		      <div class="panel-body">
		            <div class="input-group">
		                <input type="text" class="form-control" aria-label="...">
		                <div class="input-group-btn">
		                    <button type="button" class="btn btn-default">Alterar </button>
		                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <span class="caret"></span></button>
		                    <ul class="dropdown-menu dropdown-menu-right">
		                        <li><a href="#">Concluir</a></li>
		                        <li><a href="#">Abrir</a></li>
		                        <li role="separator" class="divider"></li>
		                        <li><a href="#">Excluir</a></li>
		                    </ul>
		                </div>
		            </div>
		      </div>
		    </div>
		  </div>
		  <div class="panel panel-primary">
		    <div class="panel-heading" role="tab" id="heading2">
		      <h4 class="panel-title">
		        <a class="lista-todo collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse2" aria-expanded="false" aria-controls="collapse2">
		            Tarefa 2
		        </a>
		      </h4>
		    </div>
		    <div id="collapse2" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading2">
		      <div class="panel-body">
		            <div class="input-group">
		                <input type="text" class="form-control" aria-label="...">
		                <div class="input-group-btn">
		                    <button type="button" class="btn btn-default">Alterar </button>
		                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <span class="caret"></span></button>
		                    <ul class="dropdown-menu dropdown-menu-right">
		                        <li><a href="#">Concluir</a></li>
		                        <li><a href="#">Abrir</a></li>
		                        <li role="separator" class="divider"></li>
		                        <li><a href="#">Excluir</a></li>
		                    </ul>
		                </div>
		            </div>
		      </div>
		    </div>
		  </div>
		  <div class="panel panel-success">
		    <div class="panel-heading" role="tab" id="heading3">
		      <h4 class="panel-title">
		        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse3" aria-expanded="false" aria-controls="collapse3">
		            Tarefa 3
		        </a>
		      </h4>
		    </div>
		    <div id="collapse3" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading3">
		      <div class="panel-body">
		            <div class="input-group">
		                <input type="text" class="form-control" aria-label="...">
		                <div class="input-group-btn">
		                    <button type="button" class="btn btn-default">Alterar </button>
		                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <span class="caret"></span></button>
		                    <ul class="dropdown-menu dropdown-menu-right">
		                        <li><a href="#">Concluir</a></li>
		                        <li><a href="#">Abrir</a></li>
		                        <li role="separator" class="divider"></li>
		                        <li><a href="#">Excluir</a></li>
		                    </ul>
		                </div>
		            </div>
		      </div>
		    </div>
		  </div>
		  <div class="panel panel-info">
		    <div class="panel-heading" role="tab" id="heading3">
		      <h4 class="panel-title">
		        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse4" aria-expanded="false" aria-controls="collapse3">
		            Tarefa 4
		        </a>
		      </h4>
		    </div>
		    <div id="collapse4" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading3">
		      <div class="panel-body">
		            <div class="input-group">
		                <input type="text" class="form-control" aria-label="...">
		                <div class="input-group-btn">
		                    <button type="button" class="btn btn-default">Alterar </button>
		                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <span class="caret"></span></button>
		                    <ul class="dropdown-menu dropdown-menu-right">
		                        <li><a href="#">Concluir</a></li>
		                        <li><a href="#">Abrir</a></li>
		                        <li role="separator" class="divider"></li>
		                        <li><a href="#">Excluir</a></li>
		                    </ul>
		                </div>
		            </div>
		      </div>
		    </div>
		  </div>
		  <div class="panel panel-warning">
		    <div class="panel-heading" role="tab" id="heading3">
		      <h4 class="panel-title">
		        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse5" aria-expanded="false" aria-controls="collapse3">
		            Tarefa 5
		        </a>
		      </h4>
		    </div>
		    <div id="collapse5" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading3">
		      <div class="panel-body">
		            <div class="input-group">
		                <input type="text" class="form-control" aria-label="...">
		                <div class="input-group-btn">
		                    <button type="button" class="btn btn-default">Alterar </button>
		                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <span class="caret"></span></button>
		                    <ul class="dropdown-menu dropdown-menu-right">
		                        <li><a href="#">Concluir</a></li>
		                        <li><a href="#">Abrir</a></li>
		                        <li role="separator" class="divider"></li>
		                        <li><a href="#">Excluir</a></li>
		                    </ul>
		                </div>
		            </div>
		      </div>
		    </div>
		  </div>
		  <div class="panel panel-danger">
		    <div class="panel-heading" role="tab" id="heading3">
		      <h4 class="panel-title">
		        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse6" aria-expanded="false" aria-controls="collapse3">
		            Tarefa 6
		        </a>
		      </h4>
		    </div>
		    <div id="collapse6" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading3">
		      <div class="panel-body">
		            <div class="input-group">
		                <input type="text" class="form-control" aria-label="...">
		                <div class="input-group-btn">
		                    <button type="button" class="btn btn-default">Alterar </button>
		                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <span class="caret"></span></button>
		                    <ul class="dropdown-menu dropdown-menu-right">
		                        <li><a href="#">Concluir</a></li>
		                        <li><a href="#">Abrir</a></li>
		                        <li role="separator" class="divider"></li>
		                        <li><a href="#">Excluir</a></li>
		                    </ul>
		                </div>
		            </div>
		      </div>
		    </div>
		  </div>
		</div>
    </section>
  </ul>
{% endblock %}

app/templates/home/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Lista de Tarefas</h1>
                    <h3>A melhor ferramenta para se organizar!</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/index_modelo.html
<!DOCTYPE HTML>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8">
    <meta name="description" content="ToDo List">
    <meta name="keywords" content="TODO,List,Python,Flask,MicroFrameword">
    <meta name="author" content="Daniel Galleni">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="shortcut icon" href="caminhodoarquivo/favicon.ico" />
    <title>{{ title }} | Lista de Tarefas</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/css/todo.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='assets/img/favicon.ico') }}">
  </head>
  <body>
    <section class="container">
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container topnav">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="navbar-header">
            <a class="navbar-brand" href="{{ url_for('home.homepage') }}">
              <img alt="Brand" src="{{ url_for('static', filename='assets/img/list-0-32.png') }}">
            </a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
              <li><a href="{{ url_for('home.dashboard') }}">Tarefas</a></li>
              <li><a href="{{ url_for('autenticacao.cadastro') }}">Cadastrar-se</a></li>
              <li><a href="{{ url_for('autenticacao.entrar') }}">Entrar</a></li>
            </ul>
          </div>
        </div>
      </nav>
    </section>
    <div class="jumbotron">
      <div class="container">
        <div class="panel panel-default">
          <div class="panel-body">
            <section class="page-header">
              <div class="center-block">
                <h3>{{ title }} - Lista de tarefas</h3>
              </div>
            </section>
            <section class="app_todo_cadastro">
              <div class="panel panel-default">
                <div class="panel-heading">
                  {{ title_painel }}
                </div>
                <div class="container">                  
                  <div class="clearfix"></div>
                  {% block body %}
                  {% endblock %}
                </div>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
    <footer class="panel-footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <ul class="list-inline">
              <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
              <li><a href="{{ url_for('home.dashboard') }}">Tarefas</a></li>
              <li><a href="{{ url_for('autenticacao.cadastro') }}">Cadastro</a></li>
              <li><a href="{{ url_for('autenticacao.entrar') }}">Login</a></li>
            </ul>
            <p class="copyright text-muted small">Copyright © 2017.<br>
            Todos os direitos são reservados<br>
            Desenvolvido por <a href="https://linkedin.com/in/danielgalleni" target="_blank"><strong>@danielgalleni</strong></a></p>
          </div>
        </div>
      </div>
    </footer>
    <script src="{{ url_for('static', filename='assets/jquery/jquery-3.2.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/bootstrap/js/bootstrap.min.js') }}"></script>
  </body>
</html>